#! /bin/sh

# in case Java apps ever fail
# https://wiki.archlinux.org/title/bspwm#Problems_with_Java_applications

# bashrc should run this before bspwmrc
# . $HOME/.cache/wal/colors.sh
bspc config normal_border_color  "$color1"
bspc config active_border_color  "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color  "$color1"

pgrep -x sxhkd   > /dev/null || sxhkd &
pgrep -x picom   > /dev/null || picom &
pgrep -x polybar > /dev/null || polybar -c ~/.config/polybar/config.ini example &
pgrep -x dunst   > /dev/null || dust -conf ~/.config/dunst/dunstrc &
wal   -i ~/Pictures/wallpapers/malin.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config border_radius        1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


