#! /bin/sh
# shellcheck disable=SC2317  # for the unset -f 
# commenting paths for gf

# in case Java apps ever fail
# https://wiki.archlinux.org/title/bspwm#Problems_with_Java_applications

#TODO greenclip

_grepload() {
  pgrep -x "$1" > /dev/null || "$@" &
}


# <-- theme --> 
wal -i ~/Pictures/wallpapers/malin.jpg
# wal -i ~/Pictures/wallpapers/ -o wal-set
. /home/mytyl/.cache/wal/colors.sh
xrdb -merge ~/.cache/wal/colors.Xresources

bspc config normal_border_color  "$color1"
bspc config active_border_color  "$color2"
bspc config focused_border_color "$color4"
bspc config presel_border_color  "$color1"


# <-- processes -->
_grepload sxhkd   # ~/.config/sxhkd/sxhkdrc 
_grepload mpd     # ~/.config/mpd/mpd.conf
_grepload picom \
  --experimental-backends \
  --backend glx \
  --config ~/.config/picom/picom.conf
_grepload polybar -r -c ~/.config/polybar/config.ini example # has a launch.sh
_grepload dunst   -conf ~/.config/dunst/dunstrc


# <-- display --> 
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         3
bspc config border_radius        1
bspc config window_gap           5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# <-- rules -->
bspc rule -a Gimp        desktop='^8'    state=floating follow=on
bspc rule -a Chromium    desktop='^2'
bspc rule -a mplayer2    state=floating
bspc rule -a Kupfer.py   focus=on
bspc rule -a Screenkey   manage=off
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Solaar      state=floating follow=on
bspc rule -a ncmpcpp     state=floating follow=on
