#! /bin/sh
# shellcheck disable=SC2317  # for the unset -f 
# commenting paths for gf

# in case Java apps ever fail
# https://wiki.archlinux.org/title/bspwm#Problems_with_Java_applications

# <-- theme --> 
wal -i ~/Pictures/wallpapers/malin.jpg
. /home/mytyl/.cache/wal/colors.sh
bspc config normal_border_color  "$color1"
bspc config active_border_color  "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color  "$color1"

# <-- processes -->
pgrep -x sxhkd  > /dev/null || sxhkd &  # ~/.config/sxhkd/sxhkdrc
pgrep -x mpd    > /dev/null || mpd &    # ~/.config/mpd/mpd.conf

killall picom polybar dunst
picom &
polybar -c ~/.config/polybar/config.ini example &
dunst -conf ~/.config/dunst/dunstrc &

# <-- display --> 
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         3
bspc config border_radius        1
bspc config window_gap           5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# <-- rules -->
bspc rule -a Gimp        desktop='^8'    state=floating follow=on
bspc rule -a Chromium    desktop='^2'
bspc rule -a mplayer2    state=floating
bspc rule -a Kupfer.py   focus=on
bspc rule -a Screenkey   manage=off
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Solaar      state=floating follow=on

